image: reactnativecommunity/react-native-android:5.1

stages:
  - check

lint:
  stage: check
  script:
    - yarn install --frozen-lockfile
    - yarn run lint
  only:
    - dev
    - master
    - merge_requests

tsc:
  stage: check
  script:
    - yarn install --frozen-lockfile
    - yarn tsc
  only:
    - dev
    - master
    - merge_requests