image: reactnativecommunity/react-native-android:5.1

stages:
  - check

lint:
  stage: check
  script:
    - yarn install
    - cd ./template && yarn run lint
  only:
    - dev
    - master
    - merge_requests

tsc:
  stage: check
  script:
    - yarn install
    - cd ./template && yarn tsc
  only:
    - dev
    - master
    - merge_requests